#!/usr/src/Python-3.7.2/python
users = [
          { 'admin':True, 'active': True, 'name': 'Abhishek'},
          { 'admin':True, 'active': True, 'name': 'Neli'},
          { 'admin':False, 'active': True, 'name': 'Ashish'},
          { 'admin':True, 'active': True, 'name': 'Laxmi'},
          { 'admin':True, 'active': False, 'name': 'Rajesh'},
          { 'admin':False, 'active': True, 'name': 'Sunita'},
]

line = 1

for user in users:
    prefix = f"{line} "

    if user['admin'] and user['active']:
        prefix += "ACTIVE - (ADMIN) "

    elif user['admin']:
        prefix += "Inactive - (ADMIN) "

    elif user['active']:
        prefix += "ACTIVE - (NON-ADMIN)"

    print(prefix + user['name'])
    line +=1

